# TheHive 5.2 SSO Configuration (Keycloak OAuth2)
# Domain-SSL mode: domain-based URLs, Let's Encrypt SSL
# tokenUrl/userUrl MUST use the public SSO URL (not internal container hostname)
# Reason: Keycloak's token issuer (iss) differs between internal (http://host:8080)
# and external (https://domain) access. Using internal URLs causes issuer mismatch.
# NOTE: TheHive 5.2 Community Edition does NOT support native OAuth2 (requires Starter+ license).
#       This config is kept for reference but SSO is actually handled by
#       oauth2-proxy + hive-sso-bridge.js (see docker-compose.yml).
# Placeholders replaced at deploy time by post-deploy.py Step 6

auth {
  providers: [
    {name: session}
    {name: basic, realm: thehive}
    {name: local}
    {name: key}
    {
      name: oauth2
      clientId: "YOUR_SSO_CLIENT_ID"
      clientSecret: "WILL_BE_SET_BY_POST_DEPLOY"
      redirectUri: "https://YOUR_THEHIVE_DOMAIN/api/ssoLogin"
      responseType: "code"
      grantType: "authorization_code"
      authorizationUrl: "https://YOUR_SSO_DOMAIN/realms/YOUR_SSO_REALM/protocol/openid-connect/auth"
      authorizationHeader: "Bearer"
      tokenUrl: "https://YOUR_SSO_DOMAIN/realms/YOUR_SSO_REALM/protocol/openid-connect/token"
      userUrl: "https://YOUR_SSO_DOMAIN/realms/YOUR_SSO_REALM/protocol/openid-connect/userinfo"
      scope: ["openid", "email", "profile"]
      userIdField: "email"
    }
  ]

  sso {
    autocreate: true
    autoupdate: true
    autologin: false

    mapper: "group"

    attributes {
      login: "email"
      name: "name"
      groups: "groups"
    }

    defaultRoles: ["read"]
    defaultOrganization: "YOUR_THEHIVE_ORG_NAME"

    groups {
      mappings {
        "soc-admin"    = ["admin"]
        "soc-analyst"  = ["read", "write"]
        "soc-readonly" = ["read"]
      }
    }
  }
}

user.autoCreateOnSso: true
